### ISSUE TITLE
Iteration 2 Plan is Incorrect

### ISSUE THREAD

**Issue by jbrucker** [dzptahh/ku-polls#35]
Looks like you copied the Acceptance Criteria from someplace else,
because it lists several acceptance criteria that do not apply to Iteration 2.

The Retrospective is misformatted.
The Retrospective contains inappropriate material, such as "How to use HTML". What does that mean?

**Comment by dzptahh** [comment]
Retrosoective has already had its format updated, and I've rewritten it to be more understandable.

I didn't copy anyone for the acceptance criteria, but maybe I misunderstood and that is why my writing is unclear.
- from 8. user can go between page => If someone navigates to a poll detail page when voting is not allowed, redirect them to the polls index page and show an error message on the page.
- for this One vote per user is allowed. I'm confused since I'm working on Iteration 2 and Iteration 3 at the same time. Therefore, I wrote my acceptance criteria in reverse.
